name: faiss-service
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=13.1=hd92462c_3
  - expat=2.7.4=h7354ed3_0
  - faiss-gpu=1.8.0=py3.11_hedc54c9_0_cuda11.4.4
  - filelock=3.20.3=py311h06a4308_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py311ha78e65c_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py311h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libexpat=2.7.4=h7354ed3_0
  - libfaiss=1.8.0=h5aaf3ed_0_cuda11.4.4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.9.0.86=0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.6.1=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py311h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - sympy=1.14.0=py311h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchtriton=3.1.0=py311
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - grpcio==1.78.0
      - grpcio-tools==1.78.0
      - protobuf==6.33.5
prefix: /home/michaeltshen/anaconda3/envs/faiss-service
